spring.application.name=learning
server.port=8080
spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=update

# U produkciji ovo mora biti true (HTTPS only)
app.cookie.secure=${COOKIE_SECURE:true}

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}