spring.application.name=learning
server.port=8080
spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=update

# U produkciji ovo mora biti true (HTTPS only)
app.cookie.secure=${COOKIE_SECURE:true}